from fastapi import FastAPI, UploadFile, File
from fastapi.responses import FileResponse, JSONResponse
import uuid
import shutil
import os

from llm.llama_model import LocalLLM
from rag.rag_pipeline import RAGpipeline
from stt.speech_to_text import SpeechToText
from llm.rag_prompt import build_rag_prompt
from tts.text_to_speech import TextToSpeech
MODEL_PATH = r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\faster-whisper"

app = FastAPI()

UPLOAD_DIR = "uploads"
OUTPUT_DIR = "outputs"

os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)

@app.post("/process-audio")
async def process_audio(audio: UploadFile = File(...)):
    # ✅ Save uploaded file
    input_filename = f"{uuid.uuid4()}.m4a"
    input_path = os.path.join(UPLOAD_DIR, input_filename)

    with open(input_path, "wb") as buffer:
        shutil.copyfileobj(audio.file, buffer)

    stt=SpeechToText(MODEL_PATH)
    rag=RAGpipeline()
    
    llm = LocalLLM(
        model_path=r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\mistral\mistral-7b-instruct-v0.2.Q4_K_M.gguf"
    )

    stt.record_audio()
    result=stt.transcribe_audio()
    print("***The Result Generated by Large-Whisper Model***: ",result)
    retrieved_data=rag.retrieve(result,3)
    prompt = build_rag_prompt(retrieved_data,result)
    answer = llm.generate(prompt)
    print(answer)
    tts=TextToSpeech(r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\models\bark-small")
    audio_path = tts.synthesize(answer,r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\backend\output\response.wav")
    print("\nAudio saved at:", audio_path)

    # ✅ Return URL for Flutter
    return JSONResponse({
        "audio_url": f"http://YOUR_SERVER_IP:8000/audio/{os.path.basename(audio_path)}",
        "text": answer
    })

@app.get("/audio/{filename}")
def get_audio(filename: str):
    return FileResponse(os.path.join(OUTPUT_DIR, filename))



