from llm.llama_model import LocalLLM
from llm.rag_prompt import build_rag_prompt
from rag.rag_pipeline import RAGpipeline
from stt.speech_to_text import SpeechToText
from tts.text_to_speech import TextToSpeech
MODEL_PATH = r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\faster-whisper"
def main():

    stt=SpeechToText(MODEL_PATH)
    rag=RAGpipeline()
    
    llm = LocalLLM(
        model_path=r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\mistral\mistral-7b-instruct-v0.2.Q4_K_M.gguf"
    )

    print("Ask your Query!!")
    stt.record_audio()
    result=stt.transcribe_audio()
    print("***The Result Generated by Large-Whisper Model***: ",result)
    retrieved_data=rag.retrieve(result,3)
    prompt = build_rag_prompt(retrieved_data,result)
    answer = llm.generate(prompt)
    print(answer)
    tts=TextToSpeech(r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\models\bark-small")
    audio_path = tts.synthesize(answer,r"C:\Users\s.praveenk\Documents\Projects\Poc-AI Based Voice retrieval\backend\output\response.wav")
    print("\nAudio saved at:", audio_path)


if __name__== "__main__":
    main()

