name: myapp
description: Minimal Flutter UI for Voice RAG PoC
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  record: ^6.2.0
  just_audio: ^0.9.36
  provider: ^6.1.2
  http: ^1.2.1
  path_provider: ^2.1.3
  http_parser: ^4.0.2
  permission_handler: ^11.0.0


flutter:
  uses-material-design: true
